### ISSUE TITLE
[BUG] Playwright service is crashing -  AttributeError: 'UrlModel' object has no attribute 'timeout'

### ISSUE THREAD

**Issue by mattjoyce** [mendableai/firecrawl#222]
This report if from a self hosted system, freshly synced with upstream main

**firecrawl-api-1**
calls to playwright service result in Internal Server Error.
in exec shell run
`curl -X POST "http://playwright-service:3000/html" -H "Content-Type: application/json" -d '{"url": "https://mendable.ai", "wait": 5000}'`

**firecrawl-playwright-service-1**

```
playwright-service-1  | [2024-06-01 02:14:16 +0000] [9] [ERROR] Error in ASGI Framework
playwright-service-1  | Traceback (most recent call last):
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/task_group.py", line 27, in _handle
playwright-service-1  |     await app(scope, receive, send, sync_spawn, call_soon)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 34, in __call__
playwright-service-1  |     await self.app(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
playwright-service-1  |     await super().__call__(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
playwright-service-1  |     await self.middleware_stack(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
playwright-service-1  |     raise exc
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
playwright-service-1  |     await self.app(scope, receive, _send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
playwright-service-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
playwright-service-1  |     raise exc
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
playwright-service-1  |     await app(scope, receive, sender)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
playwright-service-1  |     await self.middleware_stack(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
playwright-service-1  |     await route.handle(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
playwright-service-1  |     await self.app(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
playwright-service-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
playwright-service-1  |     raise exc
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
playwright-service-1  |     await app(scope, receive, sender)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
playwright-service-1  |     response = await func(request)
playwright-service-1  |                ^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
playwright-service-1  |     raw_response = await run_endpoint_function(
playwright-service-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
playwright-service-1  |     return await dependant.call(**values)
playwright-service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/app/main.py", line 53, in root
playwright-service-1  |     timeout=body.timeout if body.timeout else 15000,
playwright-service-1  |                             ^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 811, in __getattr__
playwright-service-1  |     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
playwright-service-1  | AttributeError: 'UrlModel' object has no attribute 'timeout'
```

**Comment by mattjoyce** [comment]
The issue is cause because body.timeout is references here 

```
    await page.goto(
        body.url,
        wait_until="load",
        **timeout=body.timeout if body.timeout else 15000,**
    )
```

but timeout is not defined in the class
```
class UrlModel(BaseModel):
    url: str
    wait: int = None
```

I cannot find any calling code specifying timeout, but seems like a good thing to provide.
I will add timeout to the class and add a default, and update the logic.

**Comment by mattjoyce** [comment]
Fix is here : https://github.com/mendableai/firecrawl/issues/222

Tested on fresh docker images.

**Comment by rafaelsideguide** [comment]
Closing this as #224 is merged.
