### ISSUE TITLE
[BUG] Missing lock for job | Invalid token in /search

### ISSUE THREAD

**Issue by AnonymousUser1245** [mendableai/firecrawl#426]
**Describe the Bug**
After setting up a local server following CONTRIBUTING.md and SELF_HOST.md, the `/scrape` function works, `/search` gives `{"error":"Unauthorized: Invalid token"}`, and `/crawl` returns a job_id. However, the server shows the following error in the terminal:

```
Attempted to access Supabase client when it's not configured.
Error logging proxy:
Error: Supabase client is not configured.
    at Proxy.<anonymous> (/home/blake/firecrawl/apps/api/src/services/supabase.ts:45:17)
    at logScrape (/home/blake/firecrawl/apps/api/src/services/logging/scrape_log.ts:24:52)
    at scrapWithFetch (/home/blake/firecrawl/apps/api/src/scraper/WebScraper/scrapers/fetch.ts:75:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async attemptScraping (/home/blake/firecrawl/apps/api/src/scraper/WebScraper/single_url.ts:189:26)
    at async scrapSingleUrl (/home/blake/firecrawl/apps/api/src/scraper/WebScraper/single_url.ts:282:23)
    at async /home/blake/firecrawl/apps/api/src/scraper/WebScraper/index.ts:67:26
    at async Promise.all (index 0)
    at async WebScraperDataProvider.convertUrlsToDocuments (/home/blake/firecrawl/apps/api/src/scraper/WebScraper/index.ts:64:7)
    at async WebScraperDataProvider.processLinks (/home/blake/firecrawl/apps/api/src/scraper/WebScraper/index.ts:264:21)
    at async WebScraperDataProvider.handleSingleUrlsMode (/home/blake/firecrawl/apps/api/src/scraper/WebScraper/index.ts:214:21)
    at async scrapeHelper (/home/blake/firecrawl/apps/api/src/controllers/scrape.ts:55:12)
    at async scrapeController (/home/blake/firecrawl/apps/api/src/controllers/scrape.ts:136:20)
```

On the web Bull dashboard, it returns the following error:
```
Error: Missing lock for job 4faae7ab-c6a0-4932-92c5-942fa38c5311 finished
    at Object.finishedErrors (/home/blake/firecrawl/apps/api/node_modules/.pnpm/bull@4.15.0/node_modules/bull/lib/scripts.js:274:16)
    at /home/blake/firecrawl/apps/api/node_modules/.pnpm/bull@4.15.0/node_modules/bull/lib/scripts.js:261:23
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![Screenshot 2024-07-17 230844](https://github.com/user-attachments/assets/22f56285-2e60-428c-89d3-694af542d3bb)

**To Reproduce**
Steps to reproduce the issue:
1. Configure the environment or settings with the instructions in CONTRIBUTING.md and SELF_HOST.md.
2. Run the command `/scrape` which works.
3. Run the command `/search` which returns `{"error":"Unauthorized: Invalid token"}`.
4. Run the command `/crawl`, which returns a job_id but results in the errors described above.

**Expected Behavior**
It should be able to crawl and return markdown of a crawled website, and it should be able to use the search function without unauthorized errors.

**Environment (please complete the following information):**
- OS: Windows using Ubuntu through WSL. Tried Docker and encountered the same issue, so reverted to WSL.

**Comment by rafaelsideguide** [comment]
Hey @AnonymousUser1245 ! Thanks for reaching out.

For the `/search` endpoint, it looks like you need a Serper API key configured for self-hosting. Just pop into your `.env` file and add your key like this:

```yaml
...
SERPER_API_KEY=your_key_here #Set if you have a serper key you'd like to use as a search api
...
```

Regarding `/crawl`, we're fixing the missing lock for job id error in our next release. In the meantime, you can still fetch the results from your crawls using the `/crawl/status` endpoint. Check out the docs [here](https://docs.firecrawl.dev/api-reference/endpoint/status) for how to use it.

Let me know if that helps or if there’s anything else you need!

**Comment by rhyswynn** [comment]
Hi @rafaelsideguide regarding the missing lock issue, I'm getting the same error. You mentioned that is is planned to be fixed, but then you closed this as 'not planned'. Does that mean you don't plan to fix it?

**Comment by rafaelsideguide** [comment]
Hey @rhyswynn , sorry for any confusion. We're planning to release V1 next week (https://github.com/mendableai/firecrawl/pull/527), which will resolve this issue along with many others. Additionally, V1 includes multiple performance improvements. I'll close this issue once we've made the release.

**Comment by rafaelsideguide** [comment]
#527 closes this.

**Comment by ciekawy** [comment]
`Error: Missing lock for job` is still a problem
