### ISSUE TITLE
[BUG] Getting 408 when trying to run firecrawl locally

### ISSUE THREAD

**Issue by SalamanderXing** [mendableai/firecrawl#548]
**Describe the Bug**
Running locally FireCrawl gives me 408 error.

**To Reproduce**
I followed these instructions: https://github.com/mendableai/firecrawl/blob/main/CONTRIBUTING.md and started firecrawl locally, with the following `.env.local`.

```
NUM_WORKERS_PER_QUEUE=8
PORT=
HOST=
SUPABASE_ANON_TOKEN=
SUPABASE_URL=
SUPABASE_SERVICE_TOKEN=
REDIS_URL=
REDIS_RATE_LIMIT_URL=
SCRAPING_BEE_API_KEY=
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
BULL_AUTH_KEY=
LOGTAIL_KEY=
PLAYWRIGHT_MICROSERVICE_URL=
```

And tested it out with this code:

```ts
import FirecrawlApp from "@mendable/firecrawl-js";

const app = new FirecrawlApp({
    apiKey: "YOUR_API_KEY",
    apiUrl: "http://localhost:3002",
});

const content = await app.scrapeUrl(
    "https://mendable.ai",
);

console.log(content);
```

And it gives:
```
file:///Users/salamanderxing/Documents/aikosmo-scraper-railway/node_modules/@mendable/firecrawl-js/build/esm/index.js:66
                throw new Error(error.message);
                      ^

Error: Request failed with status code 408
    at FirecrawlApp.<anonymous> (file:///Users/salamanderxing/Documents/aikosmo-scraper-railway/node_modules/@mendable/firecrawl-js/build/esm/index.js:66:23)
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/salamanderxing/Documents/aikosmo-scraper-railway/node_modules/@mendable/firecrawl-js/build/esm/index.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**To Reproduce**

**Expected Behavior**
Receive a scraped 

**Environment (please complete the following information):**
- OS: macOS
- Firecrawl Version: 1.0.0
- Node.js Version: Now using Node v20.16.0 (npm 10.8.1)

**Logs**
```
> firecrawl-scraper-js@1.0.0 start
> nodemon --exec ts-node src/index.ts

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`
[2024-08-18T16:51:51.039Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:51.564Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:51.622Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:51.623Z]INFO - Master 71738 is running
[2024-08-18T16:51:51.646Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:55.437Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.492Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.507Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.577Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.641Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.650Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.657Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.702Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.754Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.773Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.825Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:55.840Z]WARN - Authentication is disabled. Supabase client will not be initialized.
[2024-08-18T16:51:56.869Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:56.956Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:56.967Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.011Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.038Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.063Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.105Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.115Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.117Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.119Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.121Z]INFO - Worker 71746 started
[2024-08-18T16:51:57.130Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.137Z]INFO - Worker 71746 listening on port 3002
[2024-08-18T16:51:57.138Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.164Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.168Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.171Z]INFO - Worker 71748 started
[2024-08-18T16:51:57.187Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.200Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.207Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.215Z]INFO - Worker 71749 started
[2024-08-18T16:51:57.219Z]INFO - Worker 71748 listening on port 3002
[2024-08-18T16:51:57.219Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.229Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.233Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.243Z]INFO - Worker 71749 listening on port 3002
[2024-08-18T16:51:57.246Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.254Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.254Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.257Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.259Z]INFO - Worker 71747 started
[2024-08-18T16:51:57.266Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.268Z]INFO - Worker 71747 listening on port 3002
[2024-08-18T16:51:57.268Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.270Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.281Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.286Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.288Z]INFO - Worker 71750 started
[2024-08-18T16:51:57.288Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.291Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.293Z]INFO - Worker 71751 started
[2024-08-18T16:51:57.295Z]INFO - Worker 71750 listening on port 3002
[2024-08-18T16:51:57.295Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.297Z]WARN - POSTHOG_API_KEY is not provided - your events will not be logged. Using MockPostHog as a fallback. See posthog.ts for more.
[2024-08-18T16:51:57.298Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.301Z]INFO - Worker 71751 listening on port 3002
[2024-08-18T16:51:57.301Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.304Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.312Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.315Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.316Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.317Z]INFO - Worker 71756 started
[2024-08-18T16:51:57.318Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.320Z]INFO - Worker 71752 started
[2024-08-18T16:51:57.323Z]INFO - Worker 71756 listening on port 3002
[2024-08-18T16:51:57.323Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.325Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.326Z]INFO - Worker 71752 listening on port 3002
[2024-08-18T16:51:57.326Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.329Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.349Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.354Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.356Z]INFO - Worker 71753 started
[2024-08-18T16:51:57.367Z]INFO - Worker 71753 listening on port 3002
[2024-08-18T16:51:57.367Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.373Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.378Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.382Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.384Z]INFO - Worker 71754 started
[2024-08-18T16:51:57.387Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.389Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.391Z]INFO - Worker 71745 started
[2024-08-18T16:51:57.391Z]INFO - Worker 71754 listening on port 3002
[2024-08-18T16:51:57.391Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.392Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.396Z]INFO - Worker 71745 listening on port 3002
[2024-08-18T16:51:57.396Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.397Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:51:57.409Z]INFO - Number of CPUs: 12 available
[2024-08-18T16:51:57.411Z]INFO - Web scraper queue created
[2024-08-18T16:51:57.412Z]INFO - Worker 71755 started
[2024-08-18T16:51:57.417Z]INFO - Worker 71755 listening on port 3002
[2024-08-18T16:51:57.417Z]INFO - For the Queue UI, open: http://0.0.0.0:3002/admin//queues
[2024-08-18T16:51:57.418Z]INFO - Connected to Redis Session Rate Limit Store!
[2024-08-18T16:52:05.078Z]WARN - You're bypassing authentication
[2024-08-18T16:52:05.079Z]WARN - You're bypassing authentication
[2024-08-18T16:53:56.862Z]WARN - You're bypassing authentication
[2024-08-18T16:53:56.862Z]WARN - You're bypassing authentication
```

**Comment by rafaelsideguide** [comment]
Hey @SalamanderXing! The name of the environment variables file must be `.env` and not `.env.local`.

**Comment by SalamanderXing** [comment]
Sorry i made a mistake creating the issue, the `.env` is set and looks like the following:

```
# ===== Required ENVS ======
NUM_WORKERS_PER_QUEUE=8
PORT=3002
HOST=0.0.0.0
REDIS_URL=redis://localhost:6379

## To turn on DB authentication, you need to set up supabase.
USE_DB_AUTHENTICATION=false

# ===== Optional ENVS ======

# Supabase Setup (used to support DB authentication, advanced logging, etc.)
SUPABASE_ANON_TOKEN=
SUPABASE_URL=
SUPABASE_SERVICE_TOKEN=

# Other Optionals
TEST_API_KEY= # use if you've set up authentication and want to test with a real API key
SCRAPING_BEE_API_KEY= #Set if you'd like to use scraping Be to handle JS blocking
OPENAI_API_KEY= # add for LLM dependednt features (image alt generation, etc.)
BULL_AUTH_KEY= #
LOGTAIL_KEY= # Use if you're configuring basic logging with logtail
PLAYWRIGHT_MICROSERVICE_URL=  # set if you'd like to run a playwright fallback
LLAMAPARSE_API_KEY= #Set if you have a llamaparse key you'd like to use to parse pdfs
SERPER_API_KEY= #Set if you have a serper key you'd like to use as a search api
SLACK_WEBHOOK_URL= # set if you'd like to send slack server health status messages
```

**Comment by rafaelsideguide** [comment]
@SalamanderXing we've split the rate limit redis from the main redis (around #417). It's possible your `.env` file is missing the `REDIS_RATE_LIMIT_URL=redis://localhost:6379`.

**Comment by SalamanderXing** [comment]
@rafaelsideguide thank you for your reply. I added it but the same issue remains. Also from the logs above `Connected to Redis Session Rate Limit Store!` it does not look like that was the issue.

**Comment by mogery** [comment]
Hi there. Are you running any workers? The main thread will wait for the worker to finish the scrape, but if you're not running any, the scrape will never happen.

**Comment by DadaL-L** [comment]
I got the same issue when my ragflow was on, but not when ragflow was off. It seemed that the redis was conflict with that in ragflow. Could someone help me confim this problem?

**Comment by JohnDotOwl** [comment]
I'm unfortunately having this issue too , it happens after awhile, say few minutes. Resources is 100% not the issue have hundreds of gb in memory and more than enough cores.
