### ISSUE TITLE
[Bug] new problem , when crawl https://qiankunli.github.io/2024/08/17/llm_pre_training.html  , error

### ISSUE THREAD

**Issue by lwdnxu** [mendableai/firecrawl#665]
error info:The text contains a special token that is not allowed: <|endoftext|>
![image](https://github.com/user-attachments/assets/fe6707a2-93a2-4fbf-bfff-82e081556c34)

**Comment by nickscamara** [comment]
We're pushing a fix for that this week!

**Comment by rafaelsideguide** [comment]
The error:

```
[2024-10-18T14:38:58.330Z]ERROR - Error occurred in request! (/v1/scrape) -- ID 768402f4f3334c3e83e76227e8c40303 -- 
{"message":"The text contains a special token that is not allowed: <|endoftext|>",
"name":"Error","stack":"Error: The text contains a special token that is not allowed: <|endoftext|>\n    at module.exports.__wbindgen_error_new (/firecrawl/apps/api/node_modules/.pnpm/@dqbd+tiktoken@1.0.15/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:421:17)\n    at wasm://wasm/01569aca:wasm-function[39]:0x32e75\n    at wasm://wasm/01569aca:wasm-function[223]:0x84816\n    at Tiktoken.encode (/firecrawl/apps/api/node_modules/.pnpm/@dqbd+tiktoken@1.0.15/node_modules/@dqbd/tiktoken/tiktoken_bg.cjs:273:18)\n    at numTokensFromString (/firecrawl/apps/api/src/lib/LLM-extraction/helpers.ts:9:26)\n    at scrapeController (/firecrawl/apps/api/src/controllers/v1/scrape.ts:100:28)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}
```
