### ISSUE TITLE
[Bug/Self-Host] Scraping in a proxy environment returns an empty response.

### ISSUE THREAD

**Issue by kouyakamada** [mendableai/firecrawl#826]
**Describe the Bug**
Following [this issue](https://github.com/mendableai/firecrawl/issues/464), we are self-hosting in a proxy environment and scraping web pages. At first there is no problem, but then a blank response is returned, and from then on, blank responses are returned all the time.

In this way:
```
{'success': True, 'data': {'markdown': '', 'rawHtml':''...
```
Checking the docker compose logs, it appears that an error is occurring in the playwright-service.
```
playwright-service-1  | [2024-10-26 02:35:56 +0000] [9] [ERROR] Error in ASGI Framework
playwright-service-1  | Traceback (most recent call last):
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/hypercorn/asyncio/task_group.py", line 27, in _handle
playwright-service-1  |     await app(scope, receive, send, sync_spawn, call_soon)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/hypercorn/app_wrappers.py", line 34, in __call__
playwright-service-1  |     await self.app(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
playwright-service-1  |     await super().__call__(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
playwright-service-1  |     await self.middleware_stack(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
playwright-service-1  |     raise exc
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
playwright-service-1  |     await self.app(scope, receive, _send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
playwright-service-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
playwright-service-1  |     raise exc
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
playwright-service-1  |     await app(scope, receive, sender)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
playwright-service-1  |     await self.middleware_stack(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
playwright-service-1  |     await route.handle(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
playwright-service-1  |     await self.app(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
playwright-service-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
playwright-service-1  |     raise exc
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
playwright-service-1  |     await app(scope, receive, sender)
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
playwright-service-1  |     response = await func(request)
playwright-service-1  |                ^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
playwright-service-1  |     raw_response = await run_endpoint_function(
playwright-service-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
playwright-service-1  |     return await dependant.call(**values)
playwright-service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/app/main.py", line 77, in root
playwright-service-1  |     context = await browser.new_context()
playwright-service-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 13460, in new_context
playwright-service-1  |     await self._impl_obj.new_context(
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_browser.py", line 127, in new_context
playwright-service-1  |     channel = await self._channel.send("newContext", params)
playwright-service-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 59, in send
playwright-service-1  |     return await self._connection.wrap_api_call(
playwright-service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
playwright-service-1  |   File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
playwright-service-1  |     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright-service-1  | playwright._impl._errors.TargetClosedError: Browser.new_context: Target page, context or browser has been closed
```

**To Reproduce**
Steps to reproduce the issue:
1. Follow the procedures [this issue](https://github.com/mendableai/firecrawl/issues/464) to self-host in a proxy environment.
2. Continuously call scraping
```
response = requests.post(
                "http://xx.xx.xx.xx:3002/v1/scrape",
                headers=HEADERS,
                json={"url": url, "formats": ["markdown", "rawHtml"]}
            )
```

**Expected Behavior**
Continuous scraping is possible.

**Environment (please complete the following information):**
Based on dokcer compose in repository.

**Comment by mogery** [comment]
Closing this as stale, as self-host proxy support and configuration has changed a lot since the ticket was submitted.

**Comment by peipeiwei303-netizen** [comment]
Blank responses usually don’t mean the page failed to load — they are caused by unstable proxy links or flawed session retention strategies.
From my experience debugging similar Playwright self-host scraping issues, inconsistent IP rotation and unreliable sticky session handling are the top culprits behind recurring TargetClosedError and empty markup results.
If anyone here is still hunting for a proxy solution that plays nicely with long-running Firecrawl Docker deployments:
Our residential proxy service [Novada](https://www.novada.com/?GithubOx) is built around crawler & Playwright workloads, with two features that help mitigate this exact error:
Tunable sticky session controls: Persist a single exit IP for custom time windows, reducing constant browser context recreation when scraping one domain repeatedly.
Background healthy node rotation: Automatically shift working proxies without terminating active browser sessions, which greatly lowers the chance of context crashes mid-scrape.
The integration setup is lightweight for Firecrawl’s Docker stack, and we provide complimentary high-tier proxy access for open-source tool maintainers who’d like to test it out.

**Comment by chenhz01** [comment]
I know this issue is closed, but sharing this for others who hit the same symptom on self-hosted setups: while debugging similar "empty response" symptoms on a proxied Windows setup, one finding saved me hours — proxy clients can intercept loopback/localhost traffic unless explicitly excluded. Adding `127.0.0.1` and `localhost` to the proxy bypass list — and re-testing with proxy env vars (`HTTP_PROXY`/`HTTPS_PROXY`) unset — isolated several cases where the failure was at the proxy layer, not the scraper layer.

Not sure it covers every setup, but for self-hosted users on corporate/VPN networks it might be worth a proxy-detection note in the troubleshooting docs (detect env proxies, warn if loopback isn't bypassed). If a troubleshooting note would ever fit, I'm happy to help.
