### ISSUE TITLE
[Self-Host] Server Error when requesting /v1/scrape endpoint on locally deployed Firecrawl service

### ISSUE THREAD

**Issue by ttomato** [mendableai/firecrawl#898]
**Describe the Issue**
I encountered a 500 Server Error while making a request to the /v1/scrape endpoint on my locally deployed Firecrawl service. The error message is as follows:
An error occurred while making the request: 500 Server Error: Internal Server Error for url: http://xx.xx.xx.xx:3002/v1/scrape

**Environment (please complete the following information):**
- OS: Ubuntu 24.04.1 LTS
- Firecrawl Version: main branch, commit 5ce4aaf0ec534d9b359a1a6e8e7c7229742212cf
- Node.js Version: v20.18.0
- Database Type and Version: redis 7.4.1

**Logs**
2024-11-13 17:37:03 info [:]: 🐂 Worker taking job 9c048160-d2f0-41c3-841d-374022dbe7fa
2024-11-13 17:37:03 info [ScrapeURL:]: Scraping URL "http://news.craneb2b.com/803/qiyexinwen.html"...
2024-11-13 17:37:03 debug [ScrapeURL:]: Engine fetch does not meet feature priority threshold
2024-11-13 17:37:03 debug [ScrapeURL:]: Engine pdf does not meet feature priority threshold
2024-11-13 17:37:03 debug [ScrapeURL:]: Engine docx does not meet feature priority threshold
2024-11-13 17:37:03 warn [ScrapeURL:]: scrapeURL: All scraping engines failed! {"module":"ScrapeURL","scrapeId":"9c048160-d2f0-41c3-841d-374022dbe7fa","scrapeURL":"http://news.craneb2b.com/803/qiyexinwen.html","error":{"fallbackList":[],"results":{},"name":"Error","message":"All scraping engines failed!","stack":"Error: All scraping engines failed!\n    at scrapeURLLoop (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/scraper/scrapeURL/index.ts:245:15)\n    at scrapeURL (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/scraper/scrapeURL/index.ts:287:30)\n    at runWebScraper (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/main/runWebScraper.ts:64:31)\n    at startWebScraperPipeline (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/main/runWebScraper.ts:24:17)\n    at processJob (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/services/queue-worker.ts:280:30)\n    at processJobInternal (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/services/queue-worker.ts:68:26)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}}
2024-11-13 17:37:03 error [:]: 🐂 Job errored 9c048160-d2f0-41c3-841d-374022dbe7fa - Error: All scraping engines failed! {}
2024-11-13 17:37:03 error [:]: undefined {"fallbackList":[],"results":{}}
2024-11-13 17:37:03 error [:]: Error: All scraping engines failed!
    at scrapeURLLoop (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/scraper/scrapeURL/index.ts:245:15)
    at scrapeURL (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/scraper/scrapeURL/index.ts:287:30)
    at runWebScraper (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/main/runWebScraper.ts:64:31)
    at startWebScraperPipeline (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/main/runWebScraper.ts:24:17)
    at processJob (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/services/queue-worker.ts:280:30)
    at processJobInternal (/home/ttomato/Development/firecrawl/firecrawl/apps/api/src/services/queue-worker.ts:68:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {}
2024-11-13 17:37:03 error [:]: Error in scrapeController: All scraping engines failed! {}

**Configuration**
# ===== Required ENVS ======
NUM_WORKERS_PER_QUEUE=8
PORT=3002
HOST=0.0.0.0
REDIS_URL=redis://localhost:6379
REDIS_RATE_LIMIT_URL=redis://localhost:6379

## To turn on DB authentication, you need to set up supabase.
USE_DB_AUTHENTICATION=false

# ===== Optional ENVS ======

# Supabase Setup (used to support DB authentication, advanced logging, etc.)
SUPABASE_ANON_TOKEN=
SUPABASE_URL=
SUPABASE_SERVICE_TOKEN=

# Other Optionals
TEST_API_KEY= # use if you've set up authentication and want to test with a real API key
SCRAPING_BEE_API_KEY= #Set if you'd like to use scraping Be to handle JS blocking
OPENAI_API_KEY= # add for LLM dependednt features (image alt generation, etc.)
BULL_AUTH_KEY= @
LOGTAIL_KEY= # Use if you're configuring basic logging with logtail
PLAYWRIGHT_MICROSERVICE_URL=  # set if you'd like to run a playwright fallback
LLAMAPARSE_API_KEY= #Set if you have a llamaparse key you'd like to use to parse pdfs
SLACK_WEBHOOK_URL= # set if you'd like to send slack server health status messages
POSTHOG_API_KEY= # set if you'd like to send posthog events like job logs
POSTHOG_HOST= # set if you'd like to send posthog events like job logs

**Additional Context**

**Comment by mogery** [comment]
Can you share what scrape options your request is using?

**Comment by ttomato** [comment]
> Can you share what scrape options your request is using?

this is the payload
payload = {
        "url":"http://news.craneb2b.com/803/qiyexinwen.html",
        "formats": ["markdown"],
        "onlyMainContent": True,
        "includeTags": [],
        "excludeTags": [],
        "headers": {},
        "waitFor": 1000,
        "mobile": False,
        "skipTlsVerification": True,
        "timeout": 1000,
        # "extract": {"schema": {}, "systemPrompt": "<string>", "prompt": "<string>"},
        "actions": [{"type": "wait", "milliseconds": 2000}],
        "location": {"country": "CN", "languages": ["zh-CN"]},
    }

**Comment by mogery** [comment]
Actions, Location and skipTlsVerification are not supported on the self-hosted version.

waitFor is only supported if you set up and configure the playwright microservice (step 3 [here](https://github.com/mendableai/firecrawl/blob/main/SELF_HOST.md#steps)).

To ensure the location is in China, you will need to run the playwright microservice on a server/computer in China, or you will need to get a Chinese proxy and configure the microservice to use it. After that you do not need to specify the location parameter.

**Comment by ttomato** [comment]
ok, got it. thanks a lot.
